parameters:
#    projet_test.example.class: Projet\TestBundle\Example

services:
#    projet_test.example:
#        class: %projet_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
