<?php

namespace Amine\ForumBundle\Entity;
use Doctrine\ORM\EntityRepository;
/**
 * SubjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubjectRepository extends EntityRepository
{

	public function getWithComments($id)
	{
		$qb = $this->createQueryBuilder('a')
			   ->where('a.id =:id')
			   ->setParameter('id',$id)
               /*->join('a.id', 'c')
               ->addSelect('c')*/;
			   /*->join('AmineForumBundle:User', 'u')
			   ->addSelect('u');*/

		return $qb->getQuery()->getResult();
	}



}