parameters:
#    projet_enseignement.example.class: Projet\EnseignementBundle\Example

services:
#    projet_enseignement.example:
#        class: %projet_enseignement.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
