user:
    pattern:  /
    defaults: { _controller: "ProjetUserBundle:User:index" }

user_show:
    pattern:  /{id}/show
    defaults: { _controller: "ProjetUserBundle:User:show" }

user_show_pseudo:
    pattern:  /{pseudo}/pseudo_show
    defaults: { _controller: "ProjetUserBundle:User:pseudoShow" }

user_new:
    pattern:  /new
    defaults: { _controller: "ProjetUserBundle:User:new" }

user_create:
    pattern:  /create
    defaults: { _controller: "ProjetUserBundle:User:create" }
    requirements: { _method: post }

user_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ProjetUserBundle:User:edit" }

user_edit_pseudo:
    pattern:  /{id}/edit_pseudo
    defaults: { _controller: "ProjetUserBundle:User:pseudo" }

user_update:
    pattern:  /{id}/update
    defaults: { _controller: "ProjetUserBundle:User:update" }
    requirements: { _method: post }

user_update_pseudo:
    pattern:  /{id}/update_pseudo
    defaults: { _controller: "ProjetUserBundle:User:updatePseudo" }
    requirements: { _method: post }

user_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ProjetUserBundle:User:delete" }
    requirements: { _method: post }
