critere:
    pattern:  /
    defaults: { _controller: "ProjetCoursBundle:Critere:index" }

critere_show:
    pattern:  /{id}/show
    defaults: { _controller: "ProjetCoursBundle:Critere:show" }

critere_new:
    pattern:  /new
    defaults: { _controller: "ProjetCoursBundle:Critere:new" }

critere_create:
    pattern:  /create
    defaults: { _controller: "ProjetCoursBundle:Critere:create" }
    requirements: { _method: post }

critere_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ProjetCoursBundle:Critere:edit" }

critere_update:
    pattern:  /{id}/update
    defaults: { _controller: "ProjetCoursBundle:Critere:update" }
    requirements: { _method: post }

critere_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ProjetCoursBundle:Critere:delete" }
    requirements: { _method: post }
