departement:
    pattern:  /
    defaults: { _controller: "ProjetCoursBundle:Departement:index" }

departement_show:
    pattern:  /{id}/show
    defaults: { _controller: "ProjetCoursBundle:Departement:show" }

departement_new:
    pattern:  /new
    defaults: { _controller: "ProjetCoursBundle:Departement:new" }

departement_create:
    pattern:  /create
    defaults: { _controller: "ProjetCoursBundle:Departement:create" }
    requirements: { _method: post }

departement_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ProjetCoursBundle:Departement:edit" }

departement_update:
    pattern:  /{id}/update
    defaults: { _controller: "ProjetCoursBundle:Departement:update" }
    requirements: { _method: post }

departement_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ProjetCoursBundle:Departement:delete" }
    requirements: { _method: post }
