enseignement_forum:
    pattern:  /{id}/forum
    defaults: { _controller: "ProjetCoursBundle:Enseignement:forum" }

enseignement_addSujet:
    pattern:  /{id}/nouveau_sujet
    defaults: { _controller: "ProjetForumBundle:Sujet:new" }

enseignement_createSujet:
    pattern:  /{id}/create
    defaults: { _controller: "ProjetForumBundle:Sujet:create" }
    requirements: { _method: post } 

enseignement_addDocument:
    pattern:  /{id}/add_document
    defaults: { _controller: "ProjetCoursBundle:Enseignement:create_document" }

enseignement_create_document:
    pattern:  /{id}/create
    defaults: { _controller: "ProjetCoursBundle:Enseignement:create_document" }
    requirements: { _method: post } 

enseignement_addDevoir:
    pattern:  /{id}/add_devoir
    defaults: { _controller: "ProjetCoursBundle:Enseignement:create_devoir" }

enseignement:
    pattern:  /
    defaults: { _controller: "ProjetCoursBundle:Enseignement:index" }

enseignement_show:
    pattern:  /{id}/show
    defaults: { _controller: "ProjetCoursBundle:Enseignement:show" }

enseignement_new:
    pattern:  /new
    defaults: { _controller: "ProjetCoursBundle:Enseignement:new" }

enseignement_create:
    pattern:  /create
    defaults: { _controller: "ProjetCoursBundle:Enseignement:create" }
    requirements: { _method: post }

enseignement_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ProjetCoursBundle:Enseignement:edit" }

enseignement_update:
    pattern:  /{id}/update
    defaults: { _controller: "ProjetCoursBundle:Enseignement:update" }
    requirements: { _method: post }

enseignement_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ProjetCoursBundle:Enseignement:delete" }
    requirements: { _method: post }
