messages_envoyer:
    pattern:  /mes_messages_envoyer
    defaults: { _controller: "ProjetUserBundle:Message:indexEnvoyer" }

messages_recu:
    pattern:  /mes_messages_recu
    defaults: { _controller: "ProjetUserBundle:Message:indexRecu" }

user_messages:
    pattern:  /mes_messages
    defaults: { _controller: "ProjetUserBundle:Message:index" }

user_messageto:
    pattern:  /messageTo/{username}
    defaults: { _controller: "ProjetUserBundle:Message:newTo" }

user_login:
    pattern:  /login
    defaults: { _controller: "ProjetUserBundle:User:login" }

ProjetUserBundle_user:
    resource: "@ProjetUserBundle/Resources/config/routing/user.yml"
    prefix:   /user

ProjetUserBundle_promotion:
    resource: "@ProjetUserBundle/Resources/config/routing/promotion.yml"
    prefix:   /promotion

ProjetUserBundle_message:
    resource: "@ProjetUserBundle/Resources/config/routing/message.yml"
    prefix:   /message

ProjetUserBundle_conversation:
    resource: "@ProjetUserBundle/Resources/config/routing/conversation.yml"
    prefix:   /conversation