Forum:
    pattern:  /forum
    defaults: { _controller: ProjetForumBundle:Sujet:index }

Sujet:
    resource:  "@ProjetForumBundle/Resources/config/routing/sujet.yml"
    prefix:    /sujet

Comment:
    resource:  "@ProjetForumBundle/Resources/config/routing/comment.yml"
    prefix:    /comment    