sujet:
    pattern:  /
    defaults: { _controller: "ProjetForumBundle:Sujet:index" }

sujet_addComment:
    pattern:  /{id}/add_comment
    defaults: { _controller: "ProjetForumBundle:Comment:new" }

sujet_createComment:
    pattern:  /{id}/create_comment
    defaults: { _controller: "ProjetForumBundle:Comment:create" }

sujet_show:
    pattern:  /{id}/show
    defaults: { _controller: "ProjetForumBundle:Sujet:show" }

sujet_new:
    pattern:  /new
    defaults: { _controller: "ProjetForumBundle:Sujet:new" }

sujet_create:
    pattern:  /create
    defaults: { _controller: "ProjetForumBundle:Sujet:create" }
    requirements: { _method: post }

sujet_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ProjetForumBundle:Sujet:edit" }

sujet_update:
    pattern:  /{id}/update
    defaults: { _controller: "ProjetForumBundle:Sujet:update" }
    requirements: { _method: post }

sujet_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ProjetForumBundle:Sujet:delete" }
    requirements: { _method: post }
