Subject:
    resource:  "@AmineForumBundle/Resources/config/routing/subject.yml"
    prefix:    /subject

Comment:
    resource:  "@AmineForumBundle/Resources/config/routing/comment.yml"
    prefix:    /comment

User:
    resource:  "@AmineForumBundle/Resources/config/routing/user.yml"
    prefix:    /user

Accueil:
    pattern:  /
    defaults: { _controller: AmineForumBundle:Subject:index }
