Projet\CoursBundle\Entity\Enseignement:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    nom:
      type: string
      length: '60'
    visibilite:
      type: string
      length: '20'
    description:
      type: text
    actif:
      type: boolean
  lifecycleCallbacks: {  }
