<?php

namespace Projet\CoursBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EnseignementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnseignementRepository extends EntityRepository
{
}