<?php

namespace Projet\CoursBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EnseignementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnseignementRepository extends EntityRepository
{
	public function setAverageNote($cours_id)
	{
		// On passe par le QueryBuilder vide de l'EntityManager pour l'exemple
		$qb = $this->_em->createQueryBuilder();
	
		$avg = $this->_em->createQuery('SELECT AVG(eval.note) FROM ProjetCoursBundle:Evaluation eval WHERE eval.enseignement ='.$cours_id)->getSingleResult();
		$qb->update('ProjetCoursBundle:Enseignement', 'e')
		->set('e.note', $avg[1])
		->where('e.id = ?1')
		->setParameter('1', $cours_id)
		;
	
	
		return $qb->getQuery()->getResult();
	}
	
	public function findEtudiantCoursWithSujets($promotion_id)
	{
		// On passe par le QueryBuilder vide de l'EntityManager pour l'exemple
		$qb = $this->_em->createQueryBuilder();
		
		$qb->select('cs')
		->from('ProjetCoursBundle:Enseignement', 'cs')
		->where('cs.promotion = ?1')
		->setParameter('1', $promotion_id)
		->addSelect('s')
		->join('cs.sujets', 's')
		;
		
		
		return $qb->getQuery()->getResult();
	}
	
	
	
	public function findEnseignantCoursWithSujets($prof_id)
	{
		// On passe par le QueryBuilder vide de l'EntityManager pour l'exemple
		$qb = $this->_em->createQueryBuilder();
	
		$qb->select('cs')
		->from('ProjetCoursBundle:Enseignement', 'cs')
		->where('cs.enseignant = ?1')
		->setParameter('1', $prof_id)
		->addSelect('s')
		->join('cs.sujets', 's')
		;
	
	
		return $qb->getQuery()->getResult();
	}
}