parameters:
#    projet_forum.example.class: Projet\ForumBundle\Example

services:
#    projet_forum.example:
#        class: %projet_forum.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
