<?php

namespace Projet\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
	
	public function findBoiteReception($id)
	{
		
		// On passe par le QueryBuilder vide de l'EntityManager pour l'exemple
		$qb = $this->_em->createQueryBuilder();
	
		$qb->select('m')
		->from('ProjetUserBundle:Message', 'm')
		->join('m.boites', 'b')
        ->addSelect('b')
        ->where('b.user = :id')
        ->setParameter('id', $id)
		->andWhere('b.type_envoi = :recu')
		->setParameter('recu', 'receiver')
		;
		
	
		return $qb->getQuery()
		->getResult();
	}
	
	
	
	
	
	public function findBoiteEnvoi($id)
	{
	
		// On passe par le QueryBuilder vide de l'EntityManager pour l'exemple
		$qb = $this->_em->createQueryBuilder();
	
		$qb->select('m')
		->from('ProjetUserBundle:Message', 'm')
		->join('m.boites', 'b')
		->addSelect('b')
		->where('b.user = :id')
		->setParameter('id', $id)
		->andWhere('b.type_envoi = :recu')
		->setParameter('recu', 'sender')
		;
	
	
		return $qb->getQuery()
		->getResult();
	}
	
	
	
	
	
	
	public function findUserMessages($id)
	{
		// On passe par le QueryBuilder vide de l'EntityManager pour l'exemple
		$qb = $this->_em->createQueryBuilder();
	
		$qb->select('m')
			->from('ProjetUserBundle:Message', 'm')
			->where('m.user = :id')
			->setParameter('id', $id)
			->join('m.boites', 'b')
			->addSelect('b')
			->andWhere('b.user = :id')
			->setParameter('id', $id)
			->andWhere($qb->expr()->in('b.type_envoi', array('sender','receiver')))
		;
	
		return $qb->getQuery()
		->getResult();
	}
	
	
}