<?php

namespace Projet\ForumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SujetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SujetRepository extends EntityRepository
{
}